# <center>Centro Universitário Facens<br/></center>
<center>
<img src="https://lh4.googleusercontent.com/AsgtrT2BZGQTFAeXl4TCXZuMjWnstvzfktjcTyYbPpwgY72a0kOyuh3ZLUVFcWLPBQYfX002B-X8a9sK_iTJSNMh26pFYniAjwir4sAyPPObSRSMitOHd8WyYc46Vfts-A=w1280"/> 
</center>
  
<font size="3"><center>Prof. Renato Moraes Silva</center></font>
<br/>

# <center>Introdução ao Python</center>

Neste tutorial, são apresentados alguns recursos básicos do Python que geralmente são necessários nos projetos de Ciência de Dados. 

Para isso, estamos usando um notebook, onde é possível adicionar blocos de texto e código. Os blocos de texto podem ser adicionados usando *markdown*, HTML e LaTeX. Por exemplo, abaixo foi criada uma equação em LaTeX:   

$$ \sum_{i=1}^{n} x_i - y_i^2 $$

# Variáveis

No Python, não é preciso **declarar** as variáveis.

Os tipos básicos de variáveis são:
- int: números inteiros
- float: números reais
- str: textos

Para converter um tipo de variável para outro, pode-se usar as funções: **float**, **str** ou **int**. 

Para imprimir uma variável, basta usar **print (nome_variavel)** ou **display(nome_variavel)**. A segunda opção geralmente apresenta a impressão de uma maneira mais agradável visualmente. 

# Bibliotecas

O Python possui inúmeras bibliotecas disponibilizadas na distribuição padrão e também pela comunidade. Quando uma biblioteca não está disponível na distribuição padrão do Python, geralmente para instalá-la deve-se usar o comando: **pip install nomeDaBiblioteca". 

Para importar um biblioteca que já esteja instalada, pode-se usar: ```import nomeDaBibioteca as apelido```

### Matplotlib e Numpy

A biblioteca **matplotlib** é usada para plotar gráficos. Para usá-la, geralmente é feita a importação usando: ```import matplotlib.pyplot as plt```. 

A biblioteca **numpy** do python permite a criação, manipulações e operações matemáticas de vetores e matrizes.

### Criando vetores e matrizes

Criando um vetor com os seguintes valores $[0,1,4,9,16,25,36,49,64]]$.

Criando uma matriz com os valores: $
  \begin{bmatrix}
    0 & 0 & 0 & 0 & 0\\
    0 & 250 & 0 & 255 & 0\\
    0 & 0 & 0 & 0 & 0\\
    0 & 255 & 240 & 245 & 0\\
    0 & 0 & 0 & 0 & 0 \\
  \end{bmatrix}$

## Selecionando elementos de vetores 


Suponha que temos um vetor $[a,b,c,d,e,f,g,h,i]$. Nós podemos selecionar vários subconjuntos de elementos desse vetor, como: 

- três primeiros elementos
- todos os valores após o quinto elemento
- os três ultimos valores
- os valores entre o quinta elemento até o penúltimo elemento

**Observação**: no python, o índice começa a contar em 0.

## Operações com números

 - Soma: +
 - Subtração - 
 - Multiplicação: *
 - Divisão: /
 - Resto da divisão: %
 - Exponenciação: **
 - Raiz quadrada: use a função *sqrt()* da biblioteca numpy: ```np.sqrt(valor)```

## Criando vetores e matrizes de 0 ou 1.

Nós também podemos criar vetores e matrizes de valores zero e uma matriz de valores um.

## Estruturas de decisão

Criando operações condicionais: if e else.

## Laço de repetição *for*

## Laço de repetição *while*

## Funções

## Operações básicas com vetores e matrizes

Soma e subtração entre vetores.

Produto entre duas matrizes.

Obs.: para isso ser possível, a quantidade de colunas da primeira, deve ser igual a quantidade de linhas da segunda

A: 


array([[1, 2],
       [3, 4],
       [5, 6]])

B: 


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

A*B: 


array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

Média dos valores de uma matriz.

Desvio padrão dos valores de uma matriz.

Outras funções para vetores e matrizes.
* `np.min()` &rarr; valor mínimo
* `np.max()` &rarr; valor máximo
* `np.sort(A)` &rarr; retorna o vetor $A$ ordenado
* `np.argsort(A)` &rarr; retorna os índices do vetor $A$ ordenado
* `np.var()` &rarr; variância
* `np.shape()` &rarr; dimensões da matriz
* `np.transpose()` &rarr; transposta da matriz
* `np.concatenate(arrays, axis=numero_do_eixo)` &rarr; concatena vetores ou matrizes
* `vstack(A,B)` &rarr; empilha verticalmente
* `hstack(A,B)` &rarr; empilha horizontalmente
* `np.where(A>n)` &rarr; elementos em $A$ maiores que $n$

## Exercícios

**Ex. 1**. Crie duas matrizes com os nomes $ExA$ e $ExB$ preenchidas com os seguintes valores:

$ExA = \begin{bmatrix}
    12 & 9 & 4 & 1 \\
    11 & 5 & 8 & 1 \\
    1 & 2 & 3 & 1 \\
  \end{bmatrix}
$, 
$
ExB = \begin{bmatrix}
    1 & 5 \\
    1 & 7 \\
    1 & 9 \\
    1 & 1 \\
  \end{bmatrix}
$. Após isso, imprima as duas matrizes.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################



##########################################################################

ExA:


array([[12,  9,  4,  1],
       [11,  5,  8,  1],
       [ 1,  2,  3,  1]])

ExB:


array([[1, 5],
       [1, 7],
       [2, 9],
       [1, 1]])

**Ex. 2**. Crie uma matriz $ExC$ usando a seguinte operação: $ExC = ExA \cdot ExB$. Depois, imprima $ExC$. 

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################



##########################################################################

ExC:


array([[ 30, 160],
       [ 33, 163],
       [ 10,  47]])

**Ex. 3**. Crie uma função que retorne a média e o desvio padrão das linhas de uma matriz e a média e desvio padrão das colunas de uma matriz. Depois teste sua função com a matriz $ExC$.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################



##########################################################################

Medias linhas:  [95.  98.  28.5]
Medias colunas:  [ 24.33333333 123.33333333]
Desvio padrão linhas:  [91.92388155 91.92388155 26.1629509 ]
Desvio padrão colunas:  [12.50333289 66.1236216 ]


**Ex. 4**. Crie uma matriz $ExD$ com os valores das duas últimas colunas de $ExA$. Depois, calcule a média dos valores de $ExD$.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################



##########################################################################

[[4 1]
 [8 1]
 [3 1]]
3.0


**Ex. 5**. Crie uma matriz $ExE$ com os valores das linhas 1 e 2 e das colunas 1 e 2 de $ExA$.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################



##########################################################################

[[5 8]
 [2 3]]


**Ex. 6**. Crie e imprima uma matriz $ExF$ com 5 linhas e 2 colunas e todos os valores iguais a 0.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################



##########################################################################

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


**Ex. 7**. Crie e imprima uma matriz $ExG$ com 4 linhas e 3 colunas e todos os valores iguais a 1.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################



##########################################################################

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Ex. 8**. Crie uma função que retorne o fatorial de um número. Teste a função que você criou, calculando o fatorial de 8. 

Fórmula do fatorial: $n! = (1 * 2 * 3 * ... * (n-2) * (n-1) * n)$

Obs: é obrigatório usar um laço `for`. 

Exemplos: 
* $1! = 1$
* $2! = 1*2$
* $3! = 1*2*3$
* $4! = 1*2*3*4$
* $5! = 1*2*3*4*5$